# GitHub Action to notify Go Proxy
name: Go Proxy Notification

on:
  push:
    tags:
      - "v*"

jobs:
  notify-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Go Proxy
        run: |
          curl https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info
